import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import PWARegistrar from "./pwa-registrar"
import ClientLayout from "./client-layout"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Galery Navila",
  description: "Generated by create next app",
  generator: "v0.dev",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="id">
      <body className={inter.className}>
        <ClientLayout>
          {children}
          <PWARegistrar />
        </ClientLayout>
      </body>
    </html>
  )
}

